In [6]:
import os
import pandas as pd

In [41]:
for idx,file in enumerate(os.listdir("D:/hidden_cve/graphql2/")):
    if idx==166:
        continue
    commitsA = pd.read_csv("D:/hidden_cve/graphql2/"+file)
    try:
        commitsB = pd.read_csv("D:/hidden_cve/graphql/"+file.split("_")[1])
    except FileNotFoundError:
        continue
    res = pd.concat([commitsB.drop(["additions","deletions","commit_date"],axis=1),commitsA],axis=1)
    res.to_csv("D:/hidden_cve/graphql/"+file.split("_")[1])
    #print(idx,file,commitsA.shape,commitsB.shape,res.shape)

C:\Users\nitzan\.conda\envs\keras_gpu\lib\site-packages\IPython\core\interactiveshell.py:3251: DtypeWarning: Columns (1,2,3,5) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
C:\Users\nitzan\.conda\envs\keras_gpu\lib\site-packages\IPython\core\interactiveshell.py:3251: DtypeWarning: Columns (1,2,3,4,5) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
C:\Users\nitzan\.conda\envs\keras_gpu\lib\site-packages\IPython\core\interactiveshell.py:3251: DtypeWarning: Columns (1,3,5) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
C:\Users\nitzan\.conda\envs\keras_gpu\lib\site-packages\IPython\core\interactiveshell.py:3251: DtypeWarning: Columns (1,2,3,4) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

((59, 3), (59, 9))

In [23]:
commitsB

,vulnerabilityAlerts,forks,issues,pullRequests,releases,stargazers,additions,deletions,commit_date
0,NaN,2016-02-25T16:57:49Z,2016-05-13T21:06:42Z,2016-03-28T22:06:48Z,2016-06-28T05:29:08Z,2016-05-18T18:08:45Z,2,2,2021-04-22T15:35:24Z
1,NaN,2016-03-28T22:01:44Z,2016-06-01T07:53:53Z,2016-06-10T21:44:00Z,2016-11-21T17:30:57Z,2016-06-02T07:43:40Z,531,50,2021-04-13T15:02:57Z
2,NaN,2016-06-10T21:35:08Z,2016-06-02T07:37:01Z,2017-07-24T05:54:54Z,2016-12-22T17:22:11Z,2017-03-14T16:39:37Z,19,14,2021-02-01T16:09:43Z
3,NaN,2016-06-15T11:05:00Z,2016-06-17T16:52:39Z,2018-12-19T20:05:29Z,2017-03-10T19:42:55Z,2017-04-08T17:36:07Z,3105,1779,2020-07-21T19:06:21Z
4,NaN,2016-11-03T11:18:00Z,2016-10-31T10:29:16Z,2019-09-06T13:38:53Z,2017-04-26T15:49:48Z,2017-11-07T07:52:35Z,912,238,2020-06-10T15:41:27Z
5,NaN,2017-01-05T01:45:21Z,2016-12-28T04:26:23Z,2021-04-12T18:01:12Z,2017-09-13T15:48:59Z,2018-05-26T14:03:22Z,1330,87,2020-01-09T20:02:49Z
6,NaN,2017-04-08T17:36:08Z,2017-08-30T08:35:40Z,2021-08-31T16:31:53Z,2017-09-18T18:57:58Z,2018-06-27T16:14:55Z,12538,10765,2019-10-30T17:50:10Z
7,NaN,2017-07-24T05:52:50Z,2018-09-26T09:25:46Z,2021-12-06T20:53:57Z,2017-10-27T17:02:19Z,2018-09-26T00:39:02Z,1414,387,2019-06-24T15:55:57Z
8,NaN,2017-08-28T13:15:40Z,2018-12-19T19:28:14Z,NaN,2018-04-18T14:29:47Z,2019-05-14T09:56:19Z,504,377,2019-06-10T15:03:46Z
9,NaN,2017-11-09T05:28:02Z,2018-12-19T19:57:59Z,NaN,2018-09-29T00:17:03Z,NaN,6,6,2019-05-14T17:58:37Z
10,NaN,2018-12-19T19:35:21Z,2019-04-01T19:13:40Z,NaN,2019-01-23T19:42:39Z,NaN,240,45,2019-04-15T16:02:40Z
11,NaN,2019-02-06T08:05:49Z,2019-05-07T01:51:11Z,NaN,2019-02-05T18:11:30Z,NaN,5206,1837,2019-02-27T19:14:24Z
12,NaN,2019-02-11T18:53:49Z,2019-05-07T01:53:02Z,NaN,2019-02-11T19:13:10Z,NaN,66,37,2019-02-11T19:13:10Z
13,NaN,2019-11-01T23:41:12Z,2019-06-11T13:07:52Z,NaN,2019-02-27T19:14:24Z,NaN,6,94,2019-02-05T18:11:30Z
14,NaN,2019-11-24T15:12:59Z,NaN,NaN,2019-04-15T16:02:40Z,NaN,20199,12618,2019-01-23T19:42:39Z
15,NaN,2021-02-24T23:01:54Z,NaN,NaN,2019-05-14T17:58:37Z,NaN,51,54,2018-12-14T16:46:28Z
16,NaN,2021-08-31T11:01:50Z,NaN,NaN,2019-06-10T15:03:46Z,NaN,4,3,2018-12-06T15:52:18Z
17,NaN,2021-12-06T20:47:24Z,NaN,NaN,2019-06-24T15:55:57Z,NaN,16,8,2018-11-20T13:42:03Z
18,NaN,NaN,NaN,NaN,2019-10-30T17:50:10Z,NaN,6,2,2018-10-29T19:25:26Z
19,NaN,NaN,NaN,NaN,2020-01-09T20:02:49Z,NaN,2,2,2018-10-19T18:46:34Z
20,NaN,NaN,NaN,NaN,2020-06-10T15:41:27Z,NaN,16454,13375,2018-09-29T00:17:03Z
21,NaN,NaN,NaN,NaN,2020-07-21T19:06:21Z,NaN,11,11,2018-06-13T19:46:50Z
22,NaN,NaN,NaN,NaN,2021-02-01T16:09:43Z,NaN,2,2,2018-06-05T15:43:51Z
23,NaN,NaN,NaN,NaN,2021-04-13T15:02:57Z,NaN,0,5,2018-06-05T15:23:29Z
24,NaN,NaN,NaN,NaN,NaN,NaN,119,16,2018-05-16T19:47:22Z
25,NaN,NaN,NaN,NaN,NaN,NaN,21,9,2018-05-12T18:20:26Z
26,NaN,NaN,NaN,NaN,NaN,NaN,30348,16265,2018-04-18T14:29:47Z
27,NaN,NaN,NaN,NaN,NaN,NaN,12198,23436,2017-10-27T17:02:19Z
28,NaN,NaN,NaN,NaN,NaN,NaN,8,8,2017-09-18T18:57:58Z
29,NaN,NaN,NaN,NaN,NaN,NaN,18943,16244,2017-09-13T15:48:59Z
30,NaN,NaN,NaN,NaN,NaN,NaN,59,19,2017-04-26T15:49:48Z
31,NaN,NaN,NaN,NaN,NaN,NaN,12537,10381,2017-03-10T19:42:55Z
32,NaN,NaN,NaN,NaN,NaN,NaN,2682,1203,2016-12-22T17:22:11Z
33,NaN,NaN,NaN,NaN,NaN,NaN,6332,4350,2016-11-21T17:30:57Z
34,NaN,NaN,NaN,NaN,NaN,NaN,936,78,2016-11-16T22:16:34Z
35,NaN,NaN,NaN,NaN,NaN,NaN,1,1,2016-09-23T22:53:08Z
36,NaN,NaN,NaN,NaN,NaN,NaN,25125,6045,2016-09-23T17:55:57Z
37,NaN,NaN,NaN,NaN,NaN,NaN,13,31,2016-06-17T09:07:32Z
38,NaN,NaN,NaN,NaN,NaN,NaN,3938,1710,2016-06-02T19:49:18Z
39,NaN,NaN,NaN,NaN,NaN,NaN,0,3,2016-05-05T10:27:52Z
40,NaN,NaN,NaN,NaN,NaN,NaN,9,3,2016-05-05T10:18:40Z
41,NaN,NaN,NaN,NaN,NaN,NaN,15,18,2016-05-05T10:16:17Z
42,NaN,NaN,NaN,NaN,NaN,NaN,0,4,2016-03-15T17:52:33Z
43,NaN,NaN,NaN,NaN,NaN,NaN,6,2,2016-03-11T17:00:25Z
44,NaN,NaN,NaN,NaN,NaN,NaN,6,2,2016-03-01T21:18:14Z
45,NaN,NaN,NaN,NaN,NaN,NaN,70,41,2016-02-26T15:42:20Z
46,NaN,NaN,NaN,NaN,NaN,NaN,108,19,2016-02-16T22:18:38Z
47,NaN,NaN,NaN,NaN,NaN,NaN,938,346,2016-01-22T19:10:21Z
48,NaN,NaN,NaN,NaN,NaN,NaN,3465,2247,2015-12-22T18:56:54Z
49,NaN,NaN,NaN,NaN,NaN,NaN,0,3849,2015-12-01T18:37:45Z
50,NaN,NaN,NaN,NaN,NaN,NaN,200,0,2015-11-05T20:01:02Z
51,NaN,NaN,NaN,NaN,NaN,NaN,9851,7379,2015-11-04T00:02:12Z
52,NaN,NaN,NaN,NaN,NaN,NaN,0,4,2015-09-24T19:41:09Z
53,NaN,NaN,NaN,NaN,NaN,NaN,4,2,2015-09-24T19:18:55Z
54,NaN,NaN,NaN,NaN,NaN,NaN,5,3,2015-09-21T21:16:46Z
55,NaN,NaN,NaN,NaN,NaN,NaN,4,0,2015-09-21T15:51:54Z
56,NaN,NaN,NaN,NaN,NaN,NaN,54,44,2015-09-18T15:47:10Z
57,NaN,NaN,NaN,NaN,NaN,NaN,41,14827,2015-08-17T18:47:41Z
58,NaN,NaN,NaN,NaN,NaN,NaN,439108,0,2015-08-14T13:44:35Z